name: Docker image build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERTOKEN }} | docker login -u "<your-dockerhub-username>" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t <your-dockerhub-username>/fastapi-app:latest .
          docker push <your-dockerhub-username>/fastapi-app:latest
